### PR TITLE
Add Overview and Table of Contents

### PR DESCRIPTION
**Pull request by tapaswenipathak**
Hi folks, I am GSoD'19 applicant. I didn't find open tickets for GSoD'19 applicants. I read the GSoD'19 applicant docs https://github.com/opencollective/documentation/blob/master/projects/season-of-docs-2019.md#should-i-try-to-get-involved-in-improving-your-docs-now-to-increase-my-chances-of-being-selected. This is a sample PR  for the application fixing a GSoD'19 intern task for the application.  ref https://docs.opencollective.com/help/projects/season-of-docs-2019#our-season-of-docs-project-ideas.

### CODE REVIEW

**Comment by jaskiratsingh2000** [comment]
Looks like a minor,
I would leave this to Alanna to look into it.

Thanks

**Comment by tapaswenipathak** [comment]
Minor comment - ref https://docs.opencollective.com/help/projects/season-of-docs-2019#our-season-of-docs-project-ideas.

**Comment by tapaswenipathak** [comment]
folks, gentle reminder for review. cc @alanna.

**Comment by tapaswenipathak** [comment]
👋

**Comment by alanna** [comment]
Hi @tapaswenipathak - thanks for these suggestions. 

We will be proceeding with documentation improvements once the GSoD program begins. I don't want to move forward in bits and pieces before then, because we don't have capacity for mentorship and review outside the program, and I want to empower the selected GSoD candidate(s) to lead the changes. 

I will leave this pull request open. If the documentarian who joins our team through GSoD decides to merge these changes, it can go ahead. It will be at least another month before that can be addressed.

Thanks again for your effort and interest!

**Comment by tapaswenipathak** [comment]
Sure, ok.

**Pull request closed without merging**
