### PR TITLE
Welcome_page_patch1

### PR DESCRIPTION
**Pull request by CodeReign**
I have tried to eliminate unnecessary words that the write-up can do without, and also changed a few sentences to make Open Collective's sound more convincing and firm in it's objectives and services.

### CODE REVIEW

**Comment by alanna** [comment]
Thanks for your suggestions @kahinga99. However, I don't agree that these wording changes are improvements on the original. We aren't interested in reviewing fiddly documentation changes at this point, and are focused on substantive improvements and extensions only.

**Comment by CodeReign** [comment]
Hello Alanna,

Thank you for your honest feedback.

You mentioned that you are only focusing on substantive documentation. Do
you have any specific ones that i can check out and work on?
I would really love to work with Open Collective during GSoD and I want to
have a strong application. Please advise.

Kind regards,
Grace Kahinga

**Comment by alanna** [comment]
@kahinga99 - We will be selecting GSoD technical writers based on their proven past experience and skills, not on contributions to our documentation specifically. This is because the substantive documentation projects I'm referring to are the projects we defined for GSoD—working on those before the project timeframe is putting the cart before the horse. Thanks for your interest in helping with our documentation. I look forward to your GSoD application.

**Comment by CodeReign** [comment]
Hi Alanna,

Thank you for your response. You have been very helpful.

Kind regards,
Grace Kahinga

**Pull request closed without merging**
