### PR TITLE
Add info about incognito contributions

### LINKED ISSUE #2742: Docs are missing information about incognito contributions
Hello 👋 

I notice that the docs for OpenCollective don't have any reference to incognito contributions. As a user I'd love to know what happens when I contribute while incognito, specifically whether this hides my name from everyone (so the contribution is made completely anonymously) or just hides my name from the public view (and the collective admins can still see my name).

I poked around in the OpenCollective frontend, and noticed that there is a message detailing the behavior: https://github.com/opencollective/opencollective-frontend/blob/21f152ef6496dee351a617db3ef7730ca40b7a9c/components/faqs/ContributeAsFAQ.js#L35

Perhaps this message should be mirrored in the docs? If so, happy to open a PR to add it!

### PR DESCRIPTION
**Pull request by gallexi**
Closes https://github.com/opencollective/opencollective/issues/2742

This PR simply takes the copy that already exists on the frontend (desktop version): https://github.com/opencollective/opencollective-frontend/blob/21f152ef6496dee351a617db3ef7730ca40b7a9c/components/faqs/ContributeAsFAQ.js#L35 and adds it to the documentation. 

cc/ @contraexemplo for 👀, thanks so much for guiding me in making this PR! I'm totally happy to receive any feedback you have on whether there's a better place for this or whether we should add more information. Thanks!

### CODE REVIEW

**Comment by contraexemplo** [comment]
Hi @gallexi! I'm so happy to see your pull request! I've just returned from a long vacation and I'm slowly resuming my activities. I will review your PR tomorrow. Thank you so much!

**Comment by contraexemplo** [comment]
Fantastic. Thank you, @gallexi! Merging it right now. :tada:

**Comment by Betree** [comment]
Thanks @gallexi! 

We have a monthly tweet to thank contributors publicly, would you be ok to be included in it? If so, could you share your Twitter handle with me?

**Comment by gallexi** [comment]
Thanks so much for your help @contraexemplo!

@betree yes, thanks! It’s `@_gallexi`

**Pull request merged**
