### PR TITLE
Updated the string to  multiple Open Collectives, from an Open Collective and changed the link also

### PR DESCRIPTION
**Pull request by TG1999**
There is a little refactor in documentation needed as per requested in the issue.
Solve issue #3

### CODE REVIEW

**Comment by znarf** [comment]
Thank you for jumping on this. What's the point of linking to a search page in that case?

https://opencollective.com/search?q=open%20collective

Can you double check the issue you're trying to solve?

**Comment by TG1999** [comment]
Okay, I am getting your point thanks for this, can you suggest where should I link it.

**Comment by znarf** [comment]
The link could be https://opencollective.com/opencollective

But actually, the string should be saying that we run the company trough multiple Open Collectives, and link to https://opencollective.com/opencollectiveinc

**Comment by TG1999** [comment]
Okay, so this https://opencollective.com/opencollectiveinc should replace https://opencollective.com/search?q=open%20collective 
Am I right?

**Comment by znarf** [comment]
Yes. But the string should also be updated.

**Comment by TG1999** [comment]
Okay, now I got it making a PR for it soon.

**Review by znarf — APPROVED** [review]

**Comment by znarf** [comment]
@TG1999 would be nice to have a more descriptive title for the PR, explaining the change itself.

**Comment by TG1999** [comment]
Thanks for pointing out this I will be doing it

**Comment by TG1999** [comment]
Hi, @znarf I have changed the PR description please merge it if it looks good.

**Pull request merged**
